# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [55]:
#1) importer le DF avec pandas et seaborn

import pandas as pd
# URL 
url = 'https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv'

# Lire le fichier CSV depuis l'URL
df_insurance = pd.read_csv(url)

# Afficher le DataFrame
print(df_insurance)


#Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
#Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
#Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

     Customer          ST GENDER             Education  \
0     RB50392  Washington    NaN                Master
1     QZ44356     Arizona      F              Bachelor
2     AI49188      Nevada      F              Bachelor
3     WW63253  California      M              Bachelor
4     GA49547  Washington      M  High School or Below
...       ...         ...    ...                   ...
4003      NaN         NaN    NaN                   NaN
4004      NaN         NaN    NaN                   NaN
4005      NaN         NaN    NaN                   NaN
4006      NaN         NaN    NaN                   NaN
4007      NaN         NaN    NaN                   NaN

     Customer Lifetime Value   Income  Monthly Premium Auto  \
0                        NaN      0.0                1000.0
1                 697953.59%      0.0                  94.0
2                1288743.17%  48767.0                 108.0
3                 764586.18%      0.0                 106.0
4                 536307.65%  36357.0                  68.0
...                      ...      ...                   ...
4003                     NaN      NaN                   NaN
4004                     NaN      NaN                   NaN
4005                     NaN      NaN                   NaN
4006                     NaN      NaN                   NaN
4007                     NaN      NaN                   NaN

     Number of Open Complaints     Policy Type  Vehicle Class  \
0                       1/0/00   Personal Auto  Four-Door Car
1                       1/0/00   Personal Auto  Four-Door Car
2                       1/0/00   Personal Auto   Two-Door Car
3                       1/0/00  Corporate Auto            SUV
4                       1/0/00   Personal Auto  Four-Door Car
...                        ...             ...            ...
4003                       NaN             NaN            NaN
4004                       NaN             NaN            NaN
4005                       NaN             NaN            NaN
4006                       NaN             NaN            NaN
4007                       NaN             NaN            NaN

      Total Claim Amount
0               2.704934
1            1131.464935
2             566.472247
3             529.881344
4              17.269323
...                  ...
4003                 NaN
4004                 NaN
4005                 NaN
4006                 NaN
4007                 NaN

[4008 rows x 11 columns]

In [20]:
#2.Identify the dimensions of the dataset by determining the number of rows and columns it contains (identifier nb colonnes/lignes)
df_insurance.shape

(4008, 11)

In [24]:
#3. Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. 
#You should also provide suggestions for fixing any incorrect data types.
print(df_insurance.dtypes)

#- Customer = datatype is string --> appropriate for the nature of the variable

#- ST = datatype is string --> appropriate for the nature of the variable

#- GENDER = datatype is string --> appropriate for the nature of the variable

#- Education = datatype is string --> appropriate for the nature of the variable

#- Customer Lifetime Value = datatype is string --> NOT appropriate for the nature of the variable (à convertir en float)

#- Income = datatype is numerical --> NOT appropriate for the nature of the variable (à convertir en int)

#- Monthly Premium Auto = datatype is numerical --> appropriate for the nature of the variable

#- Number of Open Complaints = datatype is string --> NOT appropriate for the nature of the variable (à convertir en int)

#- Policy Type = datatype is string --> appropriate for the nature of the variable

#- Vehicle Class = datatype is string --> appropriate for the nature of the variable

#- Total Claim Amount = datatype is numerical --> appropriate for the nature of the variable


# Convertir les colonnes en types numériques appropriés
df['Customer Lifetime Value'] = pd.to_numeric(df['Customer Lifetime Value'], errors='coerce')
df['Income'] = pd.to_numeric(df['Income'], errors='coerce')
df['Number of Open Complaints'] = pd.to_numeric(df['Number of Open Complaints'], errors='coerce')

# Afficher les types de données après conversion
print("\nTypes de données après conversion :")
print(df.dtypes)

# Afficher les premières lignes du DataFrame pour vérifier les conversions
print("\nDataFrame après conversion :")
print(df.head())

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

Types de données après conversion :
Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints    float64
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

DataFrame après conversion :
  Customer          ST GENDER             Education  Customer Lifetime Value  \
0  RB50392  Washington    NaN                Master                      NaN
1  QZ44356     Arizona      F              Bachelor                      NaN
2  AI49188      Nevada      F              Bachelor                      NaN
3  WW63253  California      M              Bachelor                      NaN
4  GA49547  Washington      M  High School or Below                      NaN

    Income  Monthly Premium Auto  Number of Open Complaints     Policy Type  \
0      0.0                1000.0                        NaN   Personal Auto
1      0.0                  94.0                        NaN   Personal Auto
2  48767.0                 108.0                        NaN   Personal Auto
3      0.0                 106.0                        NaN  Corporate Auto
4  36357.0                  68.0                        NaN   Personal Auto

   Vehicle Class  Total Claim Amount
0  Four-Door Car            2.704934
1  Four-Door Car         1131.464935
2   Two-Door Car          566.472247
3            SUV          529.881344
4  Four-Door Car           17.269323

In [43]:
#4. Identify the number of unique values for each column and determine which columns appear to be categorical. 
#You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.

#Unique values
unique_counts = df_insurance.nunique()
print("Number of unique values per column :")
print(unique_counts)

# Empty list for loop (determine which culumns are numerical and which columns are categorical)
categorical_columns = []
numerical_columns = []

#Maximum threshold for unique values
threshold = 10

# Loop to identify categorical and numerical columns 
for column in df_insurance.columns:
    if df_insurance[column].dtype == 'object' or unique_counts[column] < threshold:
        categorical_columns.append(column)
    elif df_insurance[column].dtype in ['int64', 'float64'] and unique_counts[column] >= threshold:
        numerical_columns.append(column)

# Print the results

print("\nCategorical colums :")
print(categorical_columns)

print("\nNumerical colums :")
print(numerical_columns)

# describe the unique values of each categorical column
print("\nUnique values in categorical columns :")
for col in categorical_columns:
    print(f"\nColumn '{col}':")
    print(df_insurance[col].unique())
    
#Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. 
#You should also provide your conclusions based on these summary statistics.

# describe the range of values for numerical columns
print("\nRange of values for numerical columns :")
for col in numerical_columns:
    print(f"\nColumn'{col}':")
    print(df_insurance[col].describe())

# Résultats
print("\nData type per columns :")
print(df_insurance.dtypes)

# Insights
print("\nInsights:")
for col in categorical_columns:
    print(f"The column '{col}' contains {unique_counts[col]} unique values.")

for col in numerical_columns:
    stats = df_insurance[col].describe()
    print(f"The column '{col}' has a minimal value of {stats['min']}, a maximal value of {stats['max']}, and an average of {stats['mean']:.2f}.")

#Insights

  #Income: large wide variation in incomes with minimum values going down to 0 to almost 100k. 
  #The average is a bit higher than the median: therefore there are more incomes above the average

  #Monthly Premium Auto: there are outliers. For example, the maximum value of 35354.00 is extremely high compared to the median (83.00) (errors ?)
  #In this condition, the mean, the median and the distribution are skewed. 

  #Total Claim Amount: the mean is a bit highen than the median. The column shows a relatively symmetrical distribution.

Number of unique values per column :
Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

Categorical colums :
['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class']

Numerical colums :
['Income', 'Monthly Premium Auto', 'Total Claim Amount']

Unique values in categorical columns :

Column 'Customer':
['RB50392' 'QZ44356' 'AI49188' ... 'CW49887' 'MY31220' nan]

Column 'ST':
['Washington' 'Arizona' 'Nevada' 'California' 'Oregon' 'Cali' 'AZ' 'WA'
 nan]

Column 'GENDER':
[nan 'F' 'M' 'Femal' 'Male' 'female']

Column 'Education':
['Master' 'Bachelor' 'High School or Below' 'College' 'Bachelors' 'Doctor'
 nan]

Column 'Customer Lifetime Value':
[nan '697953.59%' '1288743.17%' ... '2031499.76%' '323912.47%'
 '899704.02%']

Column 'Number of Open Complaints':
['1/0/00' '1/2/00' '1/1/00' '1/3/00' '1/5/00' '1/4/00' nan]

Column 'Policy Type':
['Personal Auto' 'Corporate Auto' 'Special Auto' nan]

Column 'Vehicle Class':
['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury SUV' 'Sports Car'
 'Luxury Car' nan]

Range of values for numerical columns :

Column'Income':
count     1071.000000
mean     39295.701214
std      30469.427060
min          0.000000
25%      14072.000000
50%      36234.000000
75%      64631.000000
max      99960.000000
Name: Income, dtype: float64

Column'Monthly Premium Auto':
count     1071.000000
mean       193.234360
std       1601.190369
min         61.000000
25%         68.000000
50%         83.000000
75%        109.500000
max      35354.000000
Name: Monthly Premium Auto, dtype: float64

Column'Total Claim Amount':
count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

Data type per columns :
Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

Insights:
The column 'Customer' contains 1071 unique values.
The column 'ST' contains 8 unique values.
The column 'GENDER' contains 5 unique values.
The column 'Education' contains 6 unique values.
The column 'Customer Lifetime Value' contains 1027 unique values.
The column 'Number of Open Complaints' contains 6 unique values.
The column 'Policy Type' contains 3 unique values.
The column 'Vehicle Class' contains 6 unique values.
The column 'Income' has a minimal value of 0.0, a maximal value of 99960.0, and an average of 39295.70.
The column 'Monthly Premium Auto' has a minimal value of 61.0, a maximal value of 35354.0, and an average of 193.23.
The column 'Total Claim Amount' has a minimal value of 0.382107, a maximal value of 2893.239678, and an average of 404.99.

In [65]:
#Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

# Stats for categorical column
for col in categorical_columns:
    print(f"\nStatistiques pour la colonne '{col}':")
    
    # Frequency of the values
    value_counts = df_insurance[col].value_counts()
    print(f"\nFréquence des valeurs uniques :")
    print(value_counts)
    
    # % of the values
    value_proportions = df_insurance[col].value_counts(normalize=True)
    print(f"\nProportion des valeurs uniques :")
    print(value_proportions)

#Insights

   #Customer
#Nothing to report (it's not really a categorical column)


   #ST: 
#We can conclude that the most important part of the clients is located in Oregan (30%), and the least important part is located in Az (0,02)
# --> just by looking at the values proportion or frequency of valus.

  #Gender:
#There are duplicates of values (The value "F" corresponds to female, which already existed in the columns "female" and "femal". 
#Same for M and male
#There are approximately the same number of women (53%) as men (47%)

  #Education: 
#There are duplicates of values. For example, "Bachelor" and "Bachelors".
#The most part of the clients have a bachelor degree 

  #Number of open complaints:
#We can conclude that a large majority of clients (77%) have no open complaints. 

  #Policy type:
#A large part of the clients have a personal Auto insurance contract (72%).

  #Almost all the clients have either a four-door, a two door car or a SUV, and only 2% have luxury SUV or car.

Statistiques pour la colonne 'Customer':

Fréquence des valeurs uniques :
Customer
RB50392    1
HJ15383    1
AO74776    1
HQ82233    1
OL72737    1
          ..
RO26085    1
ES57969    1
JK55587    1
RN97635    1
MY31220    1
Name: count, Length: 1071, dtype: int64

Proportion des valeurs uniques :
Customer
RB50392    0.000934
HJ15383    0.000934
AO74776    0.000934
HQ82233    0.000934
OL72737    0.000934
             ...
RO26085    0.000934
ES57969    0.000934
JK55587    0.000934
RN97635    0.000934
MY31220    0.000934
Name: proportion, Length: 1071, dtype: float64

Statistiques pour la colonne 'ST':

Fréquence des valeurs uniques :
ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

Proportion des valeurs uniques :
ST
Oregon        0.298786
California    0.197012
Arizona       0.173669
Cali          0.112045
Nevada        0.091503
Washington    0.075630
WA            0.028011
AZ            0.023343
Name: proportion, dtype: float64

Statistiques pour la colonne 'GENDER':

Fréquence des valeurs uniques :
GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

Proportion des valeurs uniques :
GENDER
F         0.479036
M         0.432914
Male      0.040881
female    0.029350
Femal     0.017820
Name: proportion, dtype: float64

Statistiques pour la colonne 'Education':

Fréquence des valeurs uniques :
Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

Proportion des valeurs uniques :
Education
Bachelor                0.302521
College                 0.292250
High School or Below    0.276377
Master                  0.087768
Doctor                  0.034547
Bachelors               0.006536
Name: proportion, dtype: float64

Statistiques pour la colonne 'Customer Lifetime Value':

Fréquence des valeurs uniques :
Customer Lifetime Value
445811.34%     4
251459.20%     4
272535.64%     3
578018.22%     3
684615.03%     3
              ..
245357.08%     1
507566.27%     1
321497.94%     1
1227534.31%    1
899704.02%     1
Name: count, Length: 1027, dtype: int64

Proportion des valeurs uniques :
Customer Lifetime Value
445811.34%     0.003745
251459.20%     0.003745
272535.64%     0.002809
578018.22%     0.002809
684615.03%     0.002809
                 ...
245357.08%     0.000936
507566.27%     0.000936
321497.94%     0.000936
1227534.31%    0.000936
899704.02%     0.000936
Name: proportion, Length: 1027, dtype: float64

Statistiques pour la colonne 'Number of Open Complaints':

Fréquence des valeurs uniques :
Number of Open Complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

Proportion des valeurs uniques :
Number of Open Complaints
1/0/00    0.774977
1/1/00    0.128852
1/2/00    0.046685
1/3/00    0.031746
1/4/00    0.012138
1/5/00    0.005602
Name: proportion, dtype: float64

Statistiques pour la colonne 'Policy Type':

Fréquence des valeurs uniques :
Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Proportion des valeurs uniques :
Policy Type
Personal Auto     0.728291
Corporate Auto    0.218487
Special Auto      0.053221
Name: proportion, dtype: float64

Statistiques pour la colonne 'Vehicle Class':

Fréquence des valeurs uniques :
Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

Proportion des valeurs uniques :
Vehicle Class
Four-Door Car    0.537815
Two-Door Car     0.191410
SUV              0.185808
Sports Car       0.053221
Luxury SUV       0.018674
Luxury Car       0.013072
Name: proportion, dtype: float64

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [66]:
#Determine the 5 states where there are the fewest customers

   #Determine the frequency per state
state_counts = df_insurance['ST'].value_counts()

   #Sort values in ascending order: 
state_counts_sorted = state_counts.sort_values()

#Sélectionner les 5 états avec le moins de clients
least_common_states = state_counts_sorted.head(5)

#Afficher les résultats
print("The 5 states with the least clients, sorted in ascending order :")
print(least_common_states)

The 5 states with the least clients, sorted in ascending order :
ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [70]:
# Frequency
nb_of_policy = df_insurance['Policy Type'].value_counts()

print("Frequency per policy type :")
print(nb_of_policy)

# Identify the max
max_policy_type = nb_of_policy.idxmax()
max_policy_count = nb_of_policy.max()

print(f"\The type of policy that has the most clients is '{max_policy_type}' with {max_policy_count} contrats.")

Frequency per policy type :
Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64
\The type of policy that has the most clients is 'Personal Auto' with 780 contrats.

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [72]:
# Dataframe: personal auto
personal_auto_df = df_insurance.loc[df_insurance['Policy Type'] == 'Personal Auto']

# Dataframe: corporate auto
corporate_auto_df = df_insurance.loc[df_insurance['Policy Type'] == 'Corporate Auto']

# Calculer le revenu moyen pour chaque type de police
personal_auto_mean_income = personal_auto_df['Income'].mean()
corporate_auto_mean_income = corporate_auto_df['Income'].mean()

# Print the results
print(f"The average income of Personal Auto customers is {personal_auto_mean_income:.2f}")
print(f"The average income of Corporate Auto customers is {corporate_auto_mean_income:.2f}")

The average income of Personal Auto customers is 38180.70
The average income of Corporate Auto customers is 41390.31

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [73]:
# Step 1: Review statistics for Total Claim Amount
total_claim_stats = df_insurance['Total Claim Amount'].describe()
print("Summary statistics for Total Claim Amount:")
print(total_claim_stats)

# Step 2: Calculate the 75th percentile for Total Claim Amount
percentile_75 = df_insurance['Total Claim Amount'].quantile(0.75)
print(f"\n75th percentile for Total Claim Amount: {percentile_75}")

# Step 3: Create a DataFrame for customers with high Total Claim Amount
high_claim_customers = df_insurance[df_insurance['Total Claim Amount'] > percentile_75]
print("\nDataFrame for customers with high Total Claim Amount:")
print(high_claim_customers.head())

# Step 4: Calculate summary statistics for high claim amount customers
high_claim_stats = high_claim_customers.describe()
print("\nSummary statistics for customers with high Total Claim Amount:")
print(high_claim_stats)

Summary statistics for Total Claim Amount:
count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

75th percentile for Total Claim Amount: 532.8

DataFrame for customers with high Total Claim Amount:
   Customer          ST GENDER Education Customer Lifetime Value   Income  \
1   QZ44356     Arizona      F  Bachelor              697953.59%      0.0
2   AI49188      Nevada      F  Bachelor             1288743.17%  48767.0
17  OE15005        Cali    NaN   College              394524.16%  28855.0
23  TZ98966      Nevada    NaN  Bachelor              245019.10%      0.0
26  US89481  California    NaN  Bachelor              394637.21%      0.0

    Monthly Premium Auto Number of Open Complaints     Policy Type  \
1                   94.0                    1/0/00   Personal Auto
2                  108.0                    1/0/00   Personal Auto
17                 101.0                    1/0/00   Personal Auto
23                  73.0                    1/3/00  Corporate Auto
26                 111.0                    1/0/00   Personal Auto

    Vehicle Class  Total Claim Amount
1   Four-Door Car         1131.464935
2    Two-Door Car          566.472247
17            SUV          647.442031
23  Four-Door Car          554.376763
26  Four-Door Car          799.200000

Summary statistics for customers with high Total Claim Amount:
             Income  Monthly Premium Auto  Total Claim Amount
count    264.000000            264.000000          264.000000
mean   23677.344697            165.193182          782.228263
std    27013.483721            623.930992          292.751640
min        0.000000             63.000000          537.600000
25%        0.000000             99.000000          606.521741
50%    18807.000000            114.000000          679.597985
75%    42423.750000            133.250000          851.400000
max    99316.000000          10202.000000         2893.239678